In [2]:
import pandas as pd

### Loading Data

In [8]:
## Peek the first lines to check the separator used
!head data/campeonato-brasileiro-full.csv

"ID","rodata","data","hora","mandante","visitante","formacao_mandante","formacao_visitante","tecnico_mandante","tecnico_visitante","vencedor","arena","mandante_Placar","visitante_Placar","mandante_Estado","visitante_Estado"
"1","1","29/03/2003","16:00","Guarani","Vasco","","","","","Guarani"," Brinco de Ouro","4","2","SP","RJ"
"2","1","29/03/2003","16:00","Athletico-PR","Gremio","","","","","Athletico-PR"," Arena da Baixada","2","0","PR","RS"
"3","1","30/03/2003","16:00","Flamengo","Coritiba","","","","","-"," Maracanã","1","1","RJ","PR"
"4","1","30/03/2003","16:00","Goias","Paysandu","","","","","-"," Serra Dourada","2","2","GO","PA"
"5","1","30/03/2003","16:00","Internacional","Ponte Preta","","","","","-"," Beira Rio","1","1","RS","SP"
"6","1","30/03/2003","16:00","Criciuma","Fluminense","","","","","Criciuma"," Heriberto Hulse","2","0","SC","RJ"
"7","1","30/03/2003","16:00","Juventude","Sao Paulo","","","","","-"," Alfredo Jaconi","2","2","RS","SP"
"8","1","30/03/2003","16:00","Fortaleza","Bahia","","","","","-"," Castelão","0","0","CE","BA"
"9","1","30/03/2003","16:00","Cruzeiro","Sao Caetano","","","","","-"," Mineirão","2","2","MG","SP"

In [10]:
## How many rows
## Depending on the number of rows we may need to think in strategies for memory saving. It is not the case here.

!wc -l data/campeonato-brasileiro-full.csv

8406 data/campeonato-brasileiro-full.csv

In [14]:
## Partidas
partidas = pd.read_csv('data/campeonato-brasileiro-full.csv', index_col='ID')
partidas.head()

,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
ID,,,,,,,,,,,,,,,
1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP

In [16]:
## estatisticas
estatisticas = pd.read_csv('data/campeonato-brasileiro-estatisticas-full.csv')
estatisticas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Coritiba,0,0,NaN,0,NaN,0,0,0,0,0

In [18]:
## gols
gols = pd.read_csv('data/campeonato-brasileiro-gols.csv')
gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Rafael Sóbis,31,NaN
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Nílton Ferreira Júnior,63,NaN

In [ ]:
## cartoes
cartoes =