In [1]:
import pandas as pd
from datetime import datetime, date

### Loading Data

In [2]:
## Peek the first lines to check the separator used

!head data/campeonato-brasileiro-full.csv

"ID","rodata","data","hora","mandante","visitante","formacao_mandante","formacao_visitante","tecnico_mandante","tecnico_visitante","vencedor","arena","mandante_Placar","visitante_Placar","mandante_Estado","visitante_Estado"
"1","1","29/03/2003","16:00","Guarani","Vasco","","","","","Guarani"," Brinco de Ouro","4","2","SP","RJ"
"2","1","29/03/2003","16:00","Athletico-PR","Gremio","","","","","Athletico-PR"," Arena da Baixada","2","0","PR","RS"
"3","1","30/03/2003","16:00","Flamengo","Coritiba","","","","","-"," Maracanã","1","1","RJ","PR"
"4","1","30/03/2003","16:00","Goias","Paysandu","","","","","-"," Serra Dourada","2","2","GO","PA"
"5","1","30/03/2003","16:00","Internacional","Ponte Preta","","","","","-"," Beira Rio","1","1","RS","SP"
"6","1","30/03/2003","16:00","Criciuma","Fluminense","","","","","Criciuma"," Heriberto Hulse","2","0","SC","RJ"
"7","1","30/03/2003","16:00","Juventude","Sao Paulo","","","","","-"," Alfredo Jaconi","2","2","RS","SP"
"8","1","30/03/2003","16:00","Fortaleza","Bahia","","","","","-"," Castelão","0","0","CE","BA"
"9","1","30/03/2003","16:00","Cruzeiro","Sao Caetano","","","","","-"," Mineirão","2","2","MG","SP"

In [3]:
## How many rows
## Depending on the number of rows we may need to think in strategies for memory saving. It is not the case here.

!wc -l data/campeonato-brasileiro-full.csv

8406 data/campeonato-brasileiro-full.csv

In [4]:
## Matches

partidas = pd.read_csv('data/campeonato-brasileiro-full.csv', index_col='ID')
partidas.head()

,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
ID,,,,,,,,,,,,,,,
1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP

In [ ]:
## statistics

estatisticas = pd.read_csv('data/campeonato-brasileiro-estatisticas-full.csv')
estatisticas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Coritiba,0,0,NaN,0,NaN,0,0,0,0,0

In [ ]:
## gols

gols = pd.read_csv('data/campeonato-brasileiro-gols.csv')
gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Rafael Sóbis,31,NaN
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Nílton Ferreira Júnior,63,NaN

In [9]:
## cards

cartoes = pd.read_csv('data/campeonato-brasileiro-cartoes.csv')
cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
1,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
2,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72
3,4608,1,Vitoria,Amarelo,Marcelo Machado dos Santos,29.0,NaN,86
4,4608,1,Vitoria,Amarelo,Mansur,NaN,Zagueiro,10

In [10]:
## Data transformation

partidas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8405 entries, 1 to 8405
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rodata              8405 non-null   int64
 1   data                8405 non-null   object
 2   hora                8405 non-null   object
 3   mandante            8405 non-null   object
 4   visitante           8405 non-null   object
 5   formacao_mandante   3431 non-null   object
 6   formacao_visitante  3431 non-null   object
 7   tecnico_mandante    3795 non-null   object
 8   tecnico_visitante   3795 non-null   object
 9   vencedor            8405 non-null   object
 10  arena               8405 non-null   object
 11  mandante_Placar     8405 non-null   int64
 12  visitante_Placar    8405 non-null   int64
 13  mandante_Estado     8405 non-null   object
 14  visitante_Estado    8405 non-null   object
dtypes: int64(3), object(12)
memory usage: 1.0+ MB

In [22]:
## Lets set data type for "data" in order to assure ordering in future steps.
## Also, adds a formated date to show date in Brazil format.

partidas["data"] = pd.to_datetime(partidas["data"], dayfirst=True)
partidas["fdata"] = partidas["data"].dt.strftime("%d/%m/%Y")

partidas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8405 entries, 1 to 8405
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rodata              8405 non-null   int64
 1   data                8405 non-null   datetime64[ns]
 2   hora                8405 non-null   object
 3   mandante            8405 non-null   object
 4   visitante           8405 non-null   object
 5   formacao_mandante   3431 non-null   object
 6   formacao_visitante  3431 non-null   object
 7   tecnico_mandante    3795 non-null   object
 8   tecnico_visitante   3795 non-null   object
 9   vencedor            8405 non-null   object
 10  arena               8405 non-null   object
 11  mandante_Placar     8405 non-null   int64
 12  visitante_Placar    8405 non-null   int64
 13  mandante_Estado     8405 non-null   object
 14  visitante_Estado    8405 non-null   object
 15  fdata               8405 non-null   object
dtypes: datetime64[ns](1), int64(3), object(12)
memory usage: 1.1+ MB

### Historical aggregated measures
The idea is to retrieve information regarding last N matches of a club.

In [23]:
partidas.sort_values("data", ascending=False).head(10)

,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,fdata
ID,,,,,,,,,,,,,,,,
8405,38,2023-12-06,21:32,Vasco,Bragantino,4-4-2,4-3-3,R. Díaz,P. Faria Caixinha,Vasco,Estádio São Januário,2,1,RJ,SP,06/12/2023
8404,38,2023-12-06,21:32,Sao Paulo,Flamengo,4-2-3-1,4-2-3-1,D. Silvestre Júnior,A. Bacchi,Sao Paulo,Morumbi,1,0,SP,RJ,06/12/2023
8403,38,2023-12-06,21:32,Santos,Fortaleza,3-4-1-2,4-2-3-1,M. Fernandes,J. Vojvoda,Fortaleza,Estádio Urbano Caldeira,1,2,SP,CE,06/12/2023
8402,38,2023-12-06,21:32,Cuiaba,Athletico-PR,5-3-2,3-4-3,A. Cardoso de Oliveira,W. Carvalho,Cuiaba,Arena Pantanal,3,0,MT,PR,06/12/2023
8401,38,2023-12-06,21:32,Bahia,Atletico-MG,3-4-2-1,4-4-2,R. Ceni,L. Scolari,Bahia,Itaipava Arena Fonte Nova,4,1,BA,MG,06/12/2023
8400,38,2023-12-06,21:32,Cruzeiro,Palmeiras,4-3-3,3-4-1-2,P. Autuori de Mello,A. Moreira Ferreira,-,Mineirão,1,1,MG,SP,06/12/2023
8399,38,2023-12-06,21:32,Fluminense,Gremio,4-2-3-1,4-3-3,F. Diniz Silva,Renato Gaúcho,Gremio,Maracanã,2,3,RJ,RS,06/12/2023
8398,38,2023-12-06,21:32,Coritiba,Corinthians,4-2-3-1,4-3-3,A. Ferreira,L. Venker de Menezes,Corinthians,Couto Pereira,0,2,PR,SP,06/12/2023
8397,38,2023-12-06,21:32,Internacional,Botafogo-RJ,4-2-3-1,4-2-3-1,E. Coudet,T. Retzalff Nunes,Internacional,Estádio Beira-Rio,3,1,RS,RJ,06/12/2023
8396,38,2023-12-06,19:00,Goias,America-MG,4-1-4-1,4-5-1,M. Henrique,D. Giacomini,Goias,Estádio Hailé Pinheiro - Serrinha,1,0,GO,MG,06/12/2023

In [28]:
# Represents the team historic data
class TeamHistory:

    def __init__(self, team_name, n_matches=5, reference_date=date.today()):
        self.team_name = team_name
        self.n_matches = n_matches
        self.reference_date = reference_date
        self.history_as_host = partidas.loc[(partidas["mandante"] == team_name) & (partidas["data"] < reference_date)].sort_values("data", ascending=False).head(n_matches)
        self.history_as_away = partidas.loc[(partidas["visitante"] == team_name) & (partidas["data"] < reference_date)].sort_values("data", ascending=False).head(n_matches)
        self.history = pd.concat([self.history_as_host, self.history_as_away], ignore_index=True).sort_values("data", ascending=False)
        self.gols_as_host = int(self.history_as_host["mandante_Placar"].sum())
        self.gols_as_away = int(self.history_as_away["visitante_Placar"].sum())
        self.avg_gols_as_host = self.gols_as_host / n_matches
        self.avg_gols_as_away = self.gols_as_away / n_matches


## Function that return all matches of a given date
def get_matches(date=date.today()):
    return partidas.loc[partidas["data"] == date][["rodata", "data", "fdata", "hora", "mandante", "visitante", "vencedor", "mandante_Placar", "visitante_Placar"]]

### Get all matches of a day

In future steps, we will code a logic for define what matches should be shown currently. As now we don't have current data, lets use the last stored date.

In [29]:
## Defines which matches will be included in the home page

last_round = partidas["data"].max() 
brasileirao_matches = get_matches(last_round)
brasileirao_matches

,rodata,data,fdata,hora,mandante,visitante,vencedor,mandante_Placar,visitante_Placar
ID,,,,,,,,,
8396,38,2023-12-06,06/12/2023,19:00,Goias,America-MG,Goias,1,0
8397,38,2023-12-06,06/12/2023,21:32,Internacional,Botafogo-RJ,Internacional,3,1
8398,38,2023-12-06,06/12/2023,21:32,Coritiba,Corinthians,Corinthians,0,2
8399,38,2023-12-06,06/12/2023,21:32,Fluminense,Gremio,Gremio,2,3
8400,38,2023-12-06,06/12/2023,21:32,Cruzeiro,Palmeiras,-,1,1
8401,38,2023-12-06,06/12/2023,21:32,Bahia,Atletico-MG,Bahia,4,1
8402,38,2023-12-06,06/12/2023,21:32,Cuiaba,Athletico-PR,Cuiaba,3,0
8403,38,2023-12-06,06/12/2023,21:32,Santos,Fortaleza,Fortaleza,1,2
8404,38,2023-12-06,06/12/2023,21:32,Sao Paulo,Flamengo,Sao Paulo,1,0
8405,38,2023-12-06,06/12/2023,21:32,Vasco,Bragantino,Vasco,2,1

In [30]:
## Store it to csv

brasileirao_matches.to_csv('data/clean/brasileirao_matches.csv')

In [31]:
## Store last macthes dataframe for each time in the next round

teams = set(pd.concat([brasileirao_matches["mandante"], brasileirao_matches["visitante"]], ignore_index=True))

for team in teams:
    team_history = TeamHistory(team_name=team, reference_date=last_round)
    team_history.history.to_csv(f"data/clean/teams/{team.lower()}.csv")